export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 25,
  MAX_LIMIT: 100,
} as const;

export const LIMITS = {
  MAX_FILE_SIZE: 50 * 1024 * 1024,
  MAX_TITLE_LENGTH: 500,
  MAX_DESCRIPTION_LENGTH: 50_000,
  MAX_COMMENT_LENGTH: 10_000,
  MAX_TAG_NAME_LENGTH: 50,
  MAX_PROJECT_KEY_LENGTH: 5,
  MIN_PROJECT_KEY_LENGTH: 2,
} as const;
